places = ['New-York', 'Singapore', 'Vancouver', 'Moscow', 'Maldives']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
print(places.reverse())
print(places)
print(places.reverse())
print(places.sort())
print(places)
print(places.sort(reverse=True))
